name: equi7grid
channels:
  - defaults
dependencies:
  - atomicwrites=1.1.5=py36_0
  - attrs=18.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - colorama=0.3.9=py36h029ae33_0
  - coverage=4.5.1=py36hfa6e2cd_0
  - curl=7.60.0=h7602738_0
  - expat=2.2.5=hcc4222d_0
  - freexl=1.0.5=hfa6e2cd_0
  - gdal=2.2.2=py36hcebd033_1
  - geos=3.6.2=h9ef7328_2
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.1=h98b8871_1
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2018.0.3=0
  - jpeg=9b=hb83a4c4_2
  - kealib=1.4.7=ha5b336b_5
  - krb5=1.16.1=h038dc86_6
  - libboost=1.65.1=he51fdeb_4
  - libcurl=7.60.0=hc4dcbb0_0
  - libgdal=2.2.2=h2727f2b_1
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=hc65d273_3
  - libnetcdf=4.4.1.1=h825a56a_8
  - libpng=1.6.34=h79bbb47_0
  - libpq=10.3=hc4dcbb0_0
  - libspatialite=4.3.0a=h383548d_18
  - libssh2=1.8.0=hd619d38_4
  - libtiff=4.0.9=hb8ad9f9_1
  - libxml2=2.9.8=hadb2253_1
  - llvmlite=0.24.0=py36h6538335_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.2=py36hb217b18_0
  - mkl_random=1.0.1=py36h77b88f5_1
  - more-itertools=4.2.0=py36_0
  - nose=1.3.7=py36_2
  - numba=0.39.0=py36h830ac7b_0
  - numpy=1.14.5=py36h9fa60d3_4
  - numpy-base=1.14.5=py36h5c71026_4
  - openjpeg=2.3.0=h5ec785f_1
  - openssl=1.0.2o=h8ea7d77_0
  - pip=10.0.1=py36_0
  - pluggy=0.6.0=py36_0
  - proj4=4.9.3=hcf24537_7
  - py=1.5.4=py36_0
  - pyproj=1.9.5.1=py36_0
  - pytest=3.6.2=py36_0
  - pytest-cov=2.5.1=py36_0
  - python=3.6.6=hea74fb7_0
  - scipy=1.1.0=py36h672f292_0
  - setuptools=39.2.0=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.24.0=h7602738_0
  - tk=8.6.7=hcb92d03_3
  - vc=14.1=h0510ff6_3
  - vs2015_runtime=15.5.2=3
  - wheel=0.31.1=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - xerces-c=3.2.1=h27bfe9a_0
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h8395fce_2
  - pip:
    - pytileproj==0.0.8
